image: alpine/edge
packages:
  - openssl-dev
  - rust
  - cargo
sources:
  - https://git.sr.ht/~alosarjos/igdb-provider
secrets:
  - 3b0ba6c0-faae-412f-b343-10ecc17f6fd3
  - b14cc9e4-a7bf-462d-8c56-9d4e0489fa4c
tasks:
  - build: |
      cd igdb-provider
      cargo build
  - test: |
      set +x
      . ~/.buildsecrets
      set -x
      cd igdb-provider
      cargo test
      git describe --exact-match HEAD || complete-build
  - publish: |
      set +x
      . ~/.cargosecrets
      set -x
      cd igdb-provider
      cargo publish
triggers:
  - action: email
    condition: always
    to: José Miguel Sarasola <alosarjos@gmail.com>