image: alpine/edge
packages:
  - openssl-dev
  - rust
  - cargo
sources:
  - https://git.sr.ht/~alosarjos/igdb-provider
secrets:
  - 00f11c1f-fb64-402f-a674-a977cf05eba4
tasks:
  - build: |
      cd igdb-provider
      cargo build
  - test: |
      set +x
      . ~/.buildsecrets
      set -x
      cd igdb-provider
      cargo test